### ISSUE TITLE
Unable to run the instance

### ISSUE THREAD

**Issue by sarfarazengglb** [feathers-nuxt/template-app#6]
nodemon started
TypeError: Cannot read property 'resque' of undefined
    at Function.module.exports../src/server/jobs/index.ls.module.exports (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/index.ls:7:3)
    at Function.configure (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object../src/server/api.ls (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/api.ls:9:5)
    at __webpack_require__ (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/index.ls:4:7)
    at Object../src/server/index.ls (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/main.js:829:30)
    at __webpack_require__ (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/webpack/bootstrap:19:1)
    at /Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/Users/mohammedsarfaraz/Projects/FullstackNode/fullstack-app/dist/server/main.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

 FATAL  dev failed!                                                                                                         f3 01:04:32

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Pyroneus** [comment]
also getting this, 4 months later

**Comment by Pyroneus** [comment]
ok, it's related to installing feathers-nuxt globally and main.js being built having single backslashes instead of double backslashes for the require path of register.js
